---
- name: Learning to download images to be used in a cloud
  hosts: futurama
  gather_facts: yes

  vars:
          dir: "/tmp/images"

  tasks:
          - name: create directory
            file: 
                  path: "{{ dir }}"
                  state: directory

          - name: Get file from the url
            get_url:
  
                   url: https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-lxc.tar.gz
                   dest: "{{ dir }}"

          - name: unzip a file 
            unarchive:
                        src: "{{ dir }}/cirros-0.4.0-x86_64-lxc.tar.gz"
                        dest: "{{ dir }}"        
                        remote_src: yes
            become: yes
                       
