---
- name: Learning about tagging
  hosts: futurama

  vars:
          cargo1: "prizes for a claw crane"
          cargo2: "popcorn for popcorning enjoyment"
          cargo3: "stickers for on a rubix cube"

  vars_files:
          - ~/ans/vars/tagvars.yaml

  gather_facts: 

  tasks:
          - name: Make sure our directory exists
            file:
                    path: ~/output/
                    state: directory

          - name: Deploy orders to the crew
            template:
                    src: ~/ans/templates/orders.txt.j2
                    dest: ~/orders.txt
            tags:
                    - orders
                    - crew

          - name: Deploy the cargo manafest
            template:
                     src: ~/ans/templates/cargo_manafest.txt.j2
                     dest: ~/cargo_manafest.txt

            tags: 
                    - crew
                    - shipprep

          - name: Install nav charts
            template:
                     src: ~/ans/templates/navigation_charts.cfg.j2
                     dest: ~/navigation_charts.cfg

            tags:
                      - shipprep
                      - nav
