---
- name: Learning about the fetch module
  hosts: futurama

  vars: 
        batman: 
                - Gordon
                - Barbra
                - Riddler
                - Joker
                - Clayface
        superman:
                 - Lois
                 - Doomsday
                 - Zod

  tasks:
          - name: Employ the fetch module to grab a file
            fetch: 
                    src: secondfloor.txt
                    dest: /tmp/secondfloor.txt.{{ inventory_hostname }}
                    flat: yes

                    #         - name: Grab an entire directory (pull operation)
                    #           synchronize:
                    #                   mode: pull
                    #                   src: /tmp/
                    #                   dst: /tmp/{{ inventory_hostname }}

          - name: Learn to print stuff to the screen
            debug:
                    # msg: "Just want to print my message to the screen"
                    msg: "A charater in the batman series is {{ item }}"
            loop: "{{ batman }}"

          - name: Trying to copy a bunch of files back from a remote file
            shell: (cd /remote; find . -maxdepth 1 -type f) | cut -d'/' -f2
            register: files_to_copy

          - name: A temp look at files_to_copy
            debug: 
                   
                  var: files_to_copy.stdout_lines
                  # msg: "I am showing {{ files_to_copy }}"
                  #
                  #
          - name: Grab a blob of files defined by files_to_copy
            fetch:
                    src: "{{ item }}"
                    dest: /tmp/
            loop: "{{ files_to_copy.stdout_lines }}" 


